config/routes.rb
Rails.application.routes.draw do
  get 'healthcheck', to: proc { [200, {}, ['']] }

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
    get 'users/:id/edit', to: 'users/registrations#edit', as: :edit_other_user_registration
    match 'users/:id', to: 'users/registrations#update', via: [:patch, :put], as: :other_user_registration
    delete 'users/:id', to: 'users/registrations#destroy', as: :destroy_other_user_registration
  end

  # Defines the root path route ("/")
  root "homes#dashboard"
  resources :users, only: [:index]
  resources :osi_cas do
    collection do
      delete :delete_osis
    end
  end
  resources :osi_bookers do
    collection do
      delete :delete_osis
    end
  end
  resources :order_infomations do
    collection do
      post   :import
      get    :export
      delete :delete_order
      get    :download
      post   :download_data
      post   :update_order
      get    :ajax_download_data
    end
  end
  delete '/delete_users', to: 'users#delete_users'
  resources :tracking_histories, only: [:index, :show]
  get 'export_osi_ca', to: 'homes#download_osi', as: :export_osi_ca
end

app/models/tracking_history.rb
class TrackingHistory < ApplicationRecord
  belongs_to :user
  has_many :tracking_history_details

  delegate :username, to: :user, prefix: :user, allow_nil: true

end

app/controllers/tracking_histories_controller.rb
class TrackingHistoriesController < RoleApplicationController
  include Commons::Common

  before_action :load_per_page_params, :current_per_page, only: [:index, :show]

  def index
    trackings = TrackingHistory.all.order(date_tracking: :desc)
    @q = trackings.ransack(params[:q])
    result = @q.result.includes(:user).page(params[:page])
    @trackings = @current_per_page == Settings.item_paging_all ? result.per(trackings.count) : result.per(@current_per_page)
  end

  def show
    tracking = TrackingHistory.find_by(id: params[:id])
    return if tracking.blank?

    trackings = tracking.tracking_history_details.order(created_at: :desc)
    @q = trackings.ransack(params[:q])
    result = @q.result.page(params[:page])
    @trackings = @current_per_page == Settings.item_paging_all ? result.per(trackings.count) : result.per(@current_per_page)
  end
end

app/views/tracking_histories/index.html.erb
<%= render partial: 'layouts/sidebar'%>
<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <%= render partial: 'layouts/nav'%>
    <div class="container-fluid">
      <div class='d-flex justify-content-between'>
        <h1 class="h3 mb-2 text-gray-800">Histories</h1>
      </div>
      <div class="card shadow mb-4 js-table-checkbox-delete">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-8'>
            </div>
            <div class='col-md-4'>
              <div class='d-flex pb-3 justify-content-end'>
                <div>
                  <%= select_tag(:paging, options_for_select(Settings.item_paging, @current_per_page),
                    class: 'form-control-paging form-select') %>
                </div>
                <div id="branches__paging" class="ml-3">
                  <%= search_form_for @q, url: tracking_histories_path, class: 'd-flex' do |f| %>
                    <%= f.search_field :user_username_cont, value: params[:q].try(:[], :user_username_cont), class: 'form-control', placeholder: 'Search' %>
                    <%= f.submit 'Search', class: 'btn btn-secondary btn-outline ml-3' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Username</th>
                  <th><%= sort_link(@q, :date_tracking, 'Date') %></th>
                  <th class='text-center'>Detail</th>
                </tr>
              </thead>
              <tbody>
                <% @trackings.each do |tracking| %>
                  <tr>
                    <td><%= tracking.id %></td>
                    <td><%= tracking.user_username %></td>
                    <td><%= tracking.date_tracking %></td>
                    <td class='text-center'><%= link_to 'Detail', tracking_history_path(tracking), class: 'btn btn-secondary' %></td>

                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="pagination-flex-end">
            <%= paginate @trackings %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
</script>

app/views/tracking_histories/show.html.erb
<%= render partial: 'layouts/sidebar'%>
<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <%= render partial: 'layouts/nav'%>
    <div class="container-fluid">
      <div class='d-flex justify-content-between'>
        <h1 class="h3 mb-2 text-gray-800">Histories</h1>
      </div>
      <div class="card shadow mb-4 js-table-checkbox-delete">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-4'>
              <div class='d-flex pb-3 justify-content-start'>
                <div>
                  <%= select_tag(:paging, options_for_select(Settings.item_paging, @current_per_page),
                    class: 'form-control-paging form-select') %>
                </div>
              </div>
            </div>
          </div>

          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th><%= sort_link(@q, :created_at, 'DateTime') %></th>
                  <th>Action</th>
                  <th>Detail Action</th>
                </tr>
              </thead>
              <tbody>
                <% @trackings.each do |tracking| %>
                  <tr>
                    <td><%= tracking.created_at.strftime('%d/%m/%Y %H:%M:%S') %></td>
                    <td><%= tracking.action_submit.html_safe %></td>
                    <td><%= text_area_tag :content, tracking.content.html_safe, class: 'form-control' %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="pagination-flex-end">
            <%= paginate @trackings %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
</script>