config/routes.rb
Rails.application.routes.draw do
  get 'healthcheck', to: proc { [200, {}, ['']] }

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
    get 'users/:id/edit', to: 'users/registrations#edit', as: :edit_other_user_registration
    match 'users/:id', to: 'users/registrations#update', via: [:patch, :put], as: :other_user_registration
    delete 'users/:id', to: 'users/registrations#destroy', as: :destroy_other_user_registration
  end

  # Defines the root path route ("/")
  root "homes#dashboard"
  resources :users, only: [:index]
  resources :osi_cas do
    collection do
      delete :delete_osis
    end
  end
  resources :osi_bookers do
    collection do
      delete :delete_osis
    end
  end
  resources :order_infomations do
    collection do
      post   :import
      get    :export
      delete :delete_order
      get    :download
      post   :download_data
      post   :update_order
      get    :ajax_download_data
    end
  end
  delete '/delete_users', to: 'users#delete_users'
  resources :tracking_histories, only: [:index, :show]
  get 'export_osi_ca', to: 'homes#download_osi', as: :export_osi_ca
end

app/models/osi_booker.rb
class OsiBooker < ApplicationRecord
  validates :name, :code, :syntax_osi, presence: true, length: { maximum: 255 }
  # validate :validate_code

  private

  def validate_code
    return if Settings.osi_booker_code.include?(code) || code.blank?

    errors.add(:code, :invalid, message: ' not exists!!!')
  end
end

app/controllers/osi_bookers_controller.rb
class OsiBookersController < RoleApplicationController
  include Commons::Common

  before_action :load_per_page_params, :current_per_page, :load_osi_bookers, only: :index
  before_action :set_osi_booker, only: %i[ show edit update destroy ]

  # GET /osi_bookers or /osi_bookers.json
  def index
    @text_search = params['q']['id_or_name_or_code_or_syntax_osi_cont'] rescue ''
    @q = @osi_bookers.ransack(params[:q])
    result = @q.result.page(params[:page])
    @osi_bookers = @current_per_page == Settings.item_paging_all ? result.per(@osi_bookers.count) : result.per(@current_per_page)
  end

  # GET /osi_bookers/1 or /osi_bookers/1.json
  def show
  end

  # GET /osi_bookers/new
  def new
    @osi_booker = OsiBooker.new
  end

  # GET /osi_bookers/1/edit
  def edit
  end

  # POST /osi_bookers or /osi_bookers.json
  def create
    @osi_booker = OsiBooker.new(osi_booker_params)

    respond_to do |format|
      if @osi_booker.save
        tracking = TrackingHistory.find_or_initialize_by(date_tracking: Date.current, user_id: current_user.id)
        content ="Name: #{@osi_booker.name}; Code: #{@osi_booker.code}; Syntax: #{@osi_booker.syntax_osi}"
        tracking.tracking_history_details.build(action_submit: "Create New Osi Booker", content: content)
        tracking.save
        format.html { redirect_to osi_bookers_path, success: "Osi booker was successfully created." }
        format.json { render :show, status: :created, location: @osi_booker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @osi_booker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /osi_bookers/1 or /osi_bookers/1.json
  def update
    respond_to do |format|
      if @osi_booker.update(osi_booker_params)
        changes = @osi_ca.previous_changes
        if changes.present?
          tracking = TrackingHistory.find_or_initialize_by(date_tracking: Date.current, user_id: current_user.id)
          content = ''
          changes.each do |key, value|
            next if ['updated_at', 'created_at'].include?(key)

            content += "#{Settings.attribute_change.send(key)} updated: #{value[0]} => #{value[1]} \n"
          end
          tracking.tracking_history_details.build(action_submit: "Update Osi Booker", content: content)
          tracking.save
        end
        format.html { redirect_to osi_bookers_path, success: "Osi booker was successfully updated." }
        format.json { render :show, status: :ok, location: @osi_booker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @osi_booker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /osi_bookers/1 or /osi_bookers/1.json
  def destroy
    @osi_booker.destroy

    respond_to do |format|
      format.html { redirect_to osi_bookers_url, success: "Osi booker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_osis
    ids = JSON.parse(params['ids']).compact
    OsiBooker.where(id: ids).delete_all
    render js: 'window.location.reload();'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_osi_booker
    @osi_booker = OsiBooker.find_by(id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def osi_booker_params
    params.require(:osi_booker).permit(:name, :code, :syntax_osi)
  end

  def load_osi_bookers
    @osi_bookers = OsiBooker.accessible_by(current_ability)
  end
end

app/helpers/osi_bookers_helper.rb
module OsiBookersHelper
end

app/views/osi_bookers/_form.html.erb
<div class="form-group row">
  <div class="col-sm-6 mb-3 mb-sm-0">
    <%= f.label :name, 'Osi Booker Name', class: 'form-label' %>
    <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "Osi Booker Name", class: 'form-control form-control-user' %>
  </div>
  <div class="col-sm-6">
    <%= f.label :syntax_osi, 'Syntax Osi Booker', class: 'form-label' %>
    <%= f.text_field :syntax_osi, autocomplete: "syntax_osi", placeholder: "Syntax Osi Booker", class: 'form-control form-control-user' %>
  </div>
</div>
<div class="form-group row">
  <div class="col-sm-6 mb-3 mb-sm-0">
    <%= f.label :code, 'Osi Booker Code', class: 'form-label' %>
    <%= f.text_field :code, autofocus: true, autocomplete: "code", placeholder: "Osi Booker Code ", class: 'form-control form-control-user' %>
  </div>
</div>

app/views/osi_bookers/_osi_booker.html.erb
<div id="<%= dom_id osi_booker %>">
  <p>
    <strong>Name:</strong>
    <%= osi_booker.name %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= osi_booker.code %>
  </p>

  <p>
    <strong>Syntax osi:</strong>
    <%= osi_booker.syntax_osi %>
  </p>

</div>

app/views/osi_bookers/edit.html.erb
<%= render partial: 'layouts/sidebar'%>
<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <%= render partial: 'layouts/nav'%>
    <div class="container-fluid">
      <div class="col-md-12 ml-auto mr-auto">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">
              Osi Booker
            </h4>
          </div>
          <div class="card-body">
            <div class="col-md-12 ml-auto mr-auto">
              <%= form_for(@osi_booker, html: { local: true, data: { turbo: false }}) do |f| %>
                <%= render 'layouts/error_messages', model: f.object %>
                <%= render partial: 'form', locals: {f: f} %>
                <div class='col-md-12'>
                  <div class="text-center">
                    <%= link_to "Back to Osi CAS", osi_bookers_path, class: 'btn btn-secondary' %>
                    <%= f.submit "Update Osi CA", class: 'btn btn-primary' %>
                  </div>
                </div>
                <hr>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/osi_bookers/index.html.erb
<%= render partial: 'layouts/sidebar'%>
<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <%= render partial: 'layouts/nav'%>
    <div class="container-fluid">
      <div class='d-flex justify-content-between'>
        <h1 class="h3 mb-2 text-gray-800">List Osi Booker</h1>
        <div class='bg-white d-flex'>
          <% if (can? :create, OsiCa) %>
            <div class='mr-2'>
              <%= link_to 'Create Osi Booker', new_osi_booker_path, class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="card shadow mb-4 js-table-checkbox-delete">
        <% if flash.present? %>
          <div id='flashMessage'>
            <%= render 'layouts/flash_message', flash: flash %>
          </div>
        <% end %>
        <div class="card-body">
          <div class='row'>
            <div class='col-md-8'>
              <% if can? :delete, OsiBooker %>
                <div class="btn-delete-box">
                  <button type="button" class="btn btn-danger btn-del-min-v1 delete-box" disabled>Delete</button>
                </div>
              <% end %>
            </div>
            <div class='col-md-4'>
              <div class='d-flex pb-3 justify-content-end'>
                <div>
                  <%= select_tag(:paging, options_for_select(Settings.item_paging, @current_per_page),
                    class: 'form-control-paging form-select') %>
                </div>
                <div id="branches__paging" class="ml-3">
                  <%= search_form_for @q, url: osi_cas_path, class: 'd-flex' do |f| %>
                    <%= f.search_field :id_or_name_or_code_or_syntax_osi_cont, value: @text_search, class: 'form-control', placeholder: 'Search' %>
                    <%= f.submit 'Search', class: 'btn btn-secondary btn-outline ml-3' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <% if can? :delete, OsiBooker %>
                    <th class='text-center'>
                      <label class="input-checkbox checkbox-all m-0 pt-1">
                        <input name="btSelectAll" type="checkbox">
                        <span class="checkmark"></span>
                      </label>
                    </th>
                  <% end %>
                  <th><%= sort_link(@q, :id, 'ID') %></th>
                  <th><%= sort_link(@q, :name, 'OSI BOOKER') %></th>
                  <th><%= sort_link(@q, :code, 'OSI CODE') %></th>
                  <th><%= sort_link(@q, :syntax_osi, 'SYNTAX') %></th>
                  <% if can? :update, OsiBooker %>
                    <th>ACTION</th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <% @osi_bookers.each do |osi_booker| %>
                  <tr>
                    <% if can? :delete, OsiBooker %>
                      <td>
                        <div class="text-center">
                          <label class="input-checkbox">
                            <input data-index="0" name="btSelectItem" type="checkbox" osi-id="<%= osi_booker.id %>">
                            <span class="checkmark"></span>
                          </label>
                        </div>
                      </td>
                    <% end %>
                    <td><%= osi_booker.id %></td>
                    <td><%= osi_booker.name %></td>
                    <td><%= osi_booker.code %></td>
                    <td><%= osi_booker.syntax_osi %></td>
                    <% if can? :update, OsiBooker %>
                      <td class="text-center">
                        <%= link_to edit_osi_booker_path(osi_booker), class: 'table-action edit', data: {original_title: 'Edit'}, rel: 'tooltip' do %>
                          <i class="fa fa-edit"></i>
                        <% end %>
                      </td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="pagination-flex-end">
            <%= paginate @osi_bookers %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="modalDelete" class="modal fade in" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Confirmation</h5>
        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">Are you sure you want to delete this record?</div>
      <div class="modal-footer justify-content-center"><button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Close</button><button class="btn btn-danger" id="submitDelete" type="button">Delete</button></div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $(".checkbox-all").on("click", function() {
      var checked = $(this).find('input')[0].checked;
      $(this)
      .closest("table")
      .find("tbody :checkbox")
      .prop("checked", checked)
    });
    $("tbody :checkbox").on("click", function() {
      $(this).closest("table")
      .find(".checkbox-all input")
      .prop("checked",
        $(this)
        .closest("table")
        .find("tbody :checkbox:checked").length ==
        $(this)
        .closest("table")
        .find("tbody :checkbox").length
        );
    });
    $(document).on('change', '.input-checkbox input[type="checkbox"]', function() {
      let $tableSelect = $(this).closest('.js-table-checkbox-delete');
      let $selectall = $tableSelect.find('.input-checkbox input[name="btSelectAll"]');
      let itemCheckbox = $tableSelect.find('tbody .input-checkbox input[type="checkbox"]').length;
      let itemCheckboxChecked = $tableSelect.find('tbody .input-checkbox input[type="checkbox"]:checked').length;

      if ($selectall.is(':checked') == true) {
        $tableSelect.find('.btn-del-min-v1').attr('disabled', false);
      } else {
        $tableSelect.find('.btn-del-min-v1').attr('disabled', true);
      }

      if ($(this).attr('name') == 'btSelectAll') {
        $tableSelect.find('.input-checkbox input[type="checkbox"]').prop('checked', this.checked);
      } else {
        if (itemCheckbox == itemCheckboxChecked) {
          $selectall.prop("checked", true);
        } else {
          $selectall.prop("checked", false);
        }

        if (itemCheckboxChecked >=1 ) {
          $tableSelect.find('.btn-del-min-v1').attr('disabled', false);
        } else {
          $tableSelect.find('.btn-del-min-v1').attr('disabled', true);
        }
      }
    });
    $(document).on('click', '.delete-box', function() {
      let osiId = [];
      $(':checkbox:checked').each(function(i) {
        osiId[i] = $(this).attr('osi-id');
      });
      osiId = osiId.filter(x => x !== undefined);
      if(osiId.length > 0){
        $('#modalDelete').modal('show');
      } else {
        $('#notificationModal').modal('show');
      }
    });
    $(document).on('click', '#submitDelete', function() {
      $("#loader").addClass('loader-circle');
      $('#modalDelete').modal('hide');
      let osiId = [];
      $(':checkbox:checked').each(function(i) {
        osiId[i] = $(this).attr('osi-id');
      });
      osiId = osiId.filter(x => x !== undefined);
      $.ajax({
        url: '/osi_bookers/delete_osis',
        type:'DELETE',
        dataType:'script',
        data: {
          ids: JSON.stringify(osiId),
        },
        success: function(){
          return true;
        }
      });
    });
  });
</script>

app/views/osi_bookers/new.html.erb
<%= render partial: 'layouts/sidebar'%>
<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <%= render partial: 'layouts/nav'%>
    <div class="container-fluid">
      <div class="col-md-12 ml-auto mr-auto">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">
              Osi Booker
            </h4>
          </div>
          <div class="card-body">
            <div class="col-md-12 ml-auto mr-auto">
              <%= form_for(@osi_booker, html: { local: true, data: { turbo: false }}) do |f| %>
                <%= render 'layouts/error_messages', model: f.object %>
                <%= render partial: 'form', locals: {f: f} %>
                <div class='col-md-12'>
                  <div class="text-center">
                    <%= link_to "Back to Osi Bookers", osi_bookers_path, class: 'btn btn-secondary' %>
                    <%= f.submit "Create Osi Booker", class: 'btn btn-primary' %>
                  </div>
                </div>
                <hr>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/osi_bookers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @osi_booker %>

<div>
  <%= link_to "Edit this osi booker", edit_osi_booker_path(@osi_booker) %> |
  <%= link_to "Back to osi bookers", osi_bookers_path %>

  <%= button_to "Destroy this osi booker", @osi_booker, method: :delete %>
</div>