config/routes.rb
Rails.application.routes.draw do
  get 'healthcheck', to: proc { [200, {}, ['']] }

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
    get 'users/:id/edit', to: 'users/registrations#edit', as: :edit_other_user_registration
    match 'users/:id', to: 'users/registrations#update', via: [:patch, :put], as: :other_user_registration
    delete 'users/:id', to: 'users/registrations#destroy', as: :destroy_other_user_registration
  end

  # Defines the root path route ("/")
  root "homes#dashboard"
  resources :users, only: [:index]
  resources :osi_cas do
    collection do
      delete :delete_osis
    end
  end
  resources :osi_bookers do
    collection do
      delete :delete_osis
    end
  end
  resources :order_infomations do
    collection do
      post   :import
      get    :export
      delete :delete_order
      get    :download
      post   :download_data
      post   :update_order
      get    :ajax_download_data
    end
  end
  delete '/delete_users', to: 'users#delete_users'
  resources :tracking_histories, only: [:index, :show]
  get 'export_osi_ca', to: 'homes#download_osi', as: :export_osi_ca
end

app/models/order_infomation.rb
class OrderInfomation < ApplicationRecord
  scope :get_month, lambda {
    select("MONTH(issue_date) AS month")
  }

  scope :get_year, lambda {
    select("YEAR(issue_date) AS year")
  }

  scope :by_year, lambda { |year|
    where("YEAR(issue_date) = ?", year)
  }

  scope :by_month, lambda { |month|
    where("MONTH(issue_date) = ?", month)
  }

  scope :total_by_osi_ca, lambda {
    select('osi_ca, DATE_FORMAT(flt_date, "%Y-%m") as month_date, SUM(fare + charge) AS total_value').group('osi_ca, month_date')
  }

  scope :total_osi_ca_by_issue_date, lambda {
    select('osi_ca, DATE_FORMAT(issue_date, "%Y-%m") as month_date, SUM(total_full) AS total_value').group('osi_ca, month_date')
  }

  scope :get_month_flt, lambda {
    select("MONTH(flt_date) AS month").where.not(flt_date: nil)
  }

  scope :get_year_flt, lambda {
    select("YEAR(flt_date) AS year").where.not(flt_date: nil)
  }

  scope :by_year_flt, lambda { |year|
    where("YEAR(flt_date) = ?", year)
  }

  scope :by_month_flt, lambda { |month|
    where("MONTH(flt_date) = ?", month)
  }

  scope :order_by_class, lambda {
    order(Arel.sql("field(class_ticket, 'J', 'C', 'D', 'I', 'W', 'Z', 'U', 'Y', 'B', 'M', 'S', 'H',
                                        'K', 'L', 'Q', 'N', 'R', 'T', 'E', 'P', 'A', 'G')"))
  }

  scope :load_value_by_osi, lambda {
    select('osi_ca, DATE_FORMAT(flt_date, "%m/%Y") as month_date, SUM(fare + charge) AS total_value')
      .where.not(osi_ca: ['', nil]).where.not(flt_date: nil)
      .group('osi_ca, month_date')
  }

  scope :load_osi_ca_by_issue_date, lambda {
    select('osi_ca, DATE_FORMAT(issue_date, "%m/%Y") as month_date, SUM(total_full) AS total_value')
      .where.not(osi_ca: ['', nil])
      .group('osi_ca, month_date')
  }

  scope :load_value_by_booker, lambda {
    select('osi_booker, DATE_FORMAT(flt_date, "%m/%Y") as month_date, SUM(fare + charge) AS total_value')
      .where.not(osi_booker: ['', nil]).where.not(flt_date: nil)
      .group('osi_booker, month_date')
  }

  scope :flt_date_range, lambda { |start_date, end_date|
    where("flt_date BETWEEN ? AND ?", start_date, end_date)
  }

  scope :issue_date_range, lambda { |start_date, end_date|
    where("issue_date BETWEEN ? AND ?", start_date, end_date)
  }
end

app/controllers/order_infomations_controller.rb
class OrderInfomationsController < RoleApplicationController
  include Commons::Common
  include Commons::ValidateCommon

  before_action :load_per_page_params, :current_per_page, only: :index
  before_action :load_orders, only: [:index, :export]
  before_action :load_params_download, only: [:download, :download_data]

  def index
    @q = @orders.ransack(params[:q])
    result = @q.result.page(params[:page])
    @orders = @current_per_page == Settings.item_paging_all ? result.per(@orders.count) : result.per(@current_per_page)
  end

  def import
    @errors = []
    return @errors << 'Please choose xlsx file.' if params[:file] == Settings.undefined

    check_file_type_excel(params[:file])
    array_data = read_excel_file(params[:file].path)
    return @errors << 'File import includes 16 columns. Please check file again!' if array_data.first&.size.to_i != 16

    data = []
    osi_cas = OsiCa.all.pluck(:code)
    osi_bookers = OsiBooker.all.pluck(:code)

    array_data.each.with_index(1) do |row, index|
      break @errors << "Row #{index + 1}: Osi Ca not exists" if row[10].present? && !osi_cas.include?(row[10].to_s)
      break @errors << "Row #{index + 1}: Osi Booker not exists" if row[11].present? && !osi_bookers.include?(row[11].to_s)

      issue_date = row[0].to_date rescue nil
      type_ticket = row[5]
      break @errors << "Row #{index + 1}: Issue Date not exists" if issue_date.nil?

      flt_date = row[1]
      if flt_date.present?
        flt_date = row[1].to_date rescue nil
        if flt_date.present?
          issue_date_year = issue_date.year
          flt_date = flt_date.change(year: issue_date_year)
          case type_ticket
          when 'S'
            flt_date = flt_date.change(year: issue_date_year + 1) if flt_date < issue_date
          else
            flt_date = flt_date.change(year: issue_date_year - 1) if flt_date < issue_date
          end
        else
          flt_date = row[1]
        end
      end
      data << { issue_date: row[0], flt_date: flt_date, ticket_number: row[2], pax_name: row[3], route: row[4],
                type_ticket: row[5], pnr: row[6], coupon_status: row[7], class_ticket: row[8], ag: row[9],
                osi_ca: row[10], osi_booker: row[11], fare: row[12].to_i, charge: row[13].to_i, saler: row[15],
                nat_amt: row[12].to_i + row[13].to_i, total_full: row[14].to_i
              }
    end
    return if @errors.present?

    OrderInfomation.transaction do
      insert_order_data(data)
      tracking = TrackingHistory.find_or_initialize_by(date_tracking: Date.current, user_id: current_user.id)
      content = "#{params[:file].original_filename}"
      tracking.tracking_history_details.build(action_submit: "Import Excel !!!", content: content)
      tracking.save
      osi_cas = OsiCa.all.pluck(:code, :limit_value).to_h
      order_infomations = OrderInfomation.total_by_osi_ca
      order_infomations.each do |osi|
        osi_ca = osi_cas[osi.osi_ca]
        next if osi_ca.blank?

        if osi_ca.to_i < osi.total_value.to_i
          raise StandardError, "OSI #{osi.osi_ca}: #{osi.total_value.to_i} limit value exceeded."
        end
      end
    rescue StandardError => e
      @errors << e.message
      raise ActiveRecord::Rollback
    end
    return if @errors.present?

    # @success = ['The import was successful !!!']
  rescue StandardError => e
    @errors << e.message
  end

  def download; end

  def download_data
    @errors = []
    orders = OrderInfomation.all.order(:issue_date).order_by_class
    if params[:issue_date_range].present?
      range_date = params[:issue_date_range].split(" - ")
      start_date = range_date[0].to_date rescue nil
      end_date = range_date[1].to_date rescue nil
      orders = orders.where("issue_date BETWEEN ? AND ?", start_date, end_date)
    else
      if params[:month_issue_date].present?
        orders = orders.by_month(params[:month_issue_date])
      end

      if params[:year_issue_date].present?
        orders = orders.by_year(params[:year_issue_date])
      end
    end
    if params[:flt_date_range].present?
      range_date = params[:flt_date_range].split(" - ")
      start_date = range_date[0].to_date rescue nil
      end_date = range_date[1].to_date rescue nil
      orders = orders.where("flt_date BETWEEN ? AND ?", start_date, end_date)
    else
      if params[:month_flt_date].present?
        orders = orders.by_month_flt(params[:month_flt_date])
      end

      if params[:year_flt_date].present?
        orders = orders.by_year_flt(params[:year_flt_date])
      end
    end
    if params[:osi_ca].present?
      hash_osi_cas = OsiCa.all.map { |osi| [osi.id, osi.code] }.to_h
      osi_ca_name = params[:osi_ca].map { |osi| hash_osi_cas[osi.to_i] }
      orders = orders.where(osi_ca: osi_ca_name)
    end

    if params[:osi_booker].present?
      hash_osi_booker = OsiBooker.all.map { |osi| [osi.id, osi.code] }.to_h
      osi_booker_name = params[:osi_booker].map { |osi| hash_osi_booker[osi.to_i] }
      orders = orders.where(osi_booker: osi_booker_name)
    end
    path = "#{Rails.root}/tmp/excel"
    origin_name = "#{current_user.id}_my_sheet.xlsx"
    FileUtils.mkdir_p(path) unless File.directory?(path)
    file_path = "#{path}/#{origin_name}"
    File.delete(file_path) if File.exists?(file_path)
    if load_export_excel(file_path, orders) == :no_error
      @filename = "OSI_#{Time.now.strftime("%Y%m%d")}.xlsx"
      send_file(file_path,
                type: "text/xlsx; charset=utf-8; header=present",
                filename: @filename)
    else
      @errors << 'Cannot export Excel'
      render :download
    end
  end

  def export
    path = "#{Rails.root}/tmp/excel"
    FileUtils.mkdir_p(path) unless File.directory?(path)
    file_path = "#{path}/#{current_user.id}_my_sheet.xlsx"
    File.delete(file_path) if File.exists?(file_path)
    if load_export_excel(file_path, @orders) == :no_error
      filename = "OSI_#{Time.now.strftime("%Y%m%d")}.xlsx"
      send_file(file_path,
                type: "text/xlsx; charset=utf-8; header=present",
                filename: filename)
    else
      redirect_to order_infomations_path, danger: "Cannot export Excel"
    end
  rescue StandardError => e
    redirect_to order_infomations_path, danger: "Cannot export Excel"
  end

  def ajax_download_data
    path = "#{Rails.root}/tmp/excel"
  end

  def delete_order
    ids = JSON.parse(params['ids']).compact
    OrderInfomation.where(id: ids).delete_all
    render js: 'window.location.reload();'
  end

  def update_order
    @errors = []
    osi_cas = OsiCa.all.pluck(:code)
    osi_bookers = OsiBooker.all.pluck(:code)

    if params[:flt_date].present?
      flt_date = Date.parse(params[:flt_date]) rescue nil
      @errors << "Ticket Number #{params[:ticket_number]}: FLT Date is invalid" if flt_date.nil?
    end

    if params[:osi_ca].present? && !osi_cas.include?(params[:osi_ca].to_s)
      @errors << "Ticket Number #{params[:ticket_number]}: Osi Ca not exists"
    end
    if params[:osi_booker].present? && !osi_bookers.include?(params[:osi_booker].to_s)
      @errors << "Ticket Number #{params[:ticket_number]}: Osi Booker not exists"
    end
    return if @errors.present?

    OrderInfomation.transaction do
      order = OrderInfomation.find_by(id: params[:osi_id])
      return unless order.present?

      order.attributes = { flt_date: flt_date, ag: params[:ag], osi_ca: params[:osi_ca], osi_booker: params[:osi_booker],
                           coupon_status: params[:coupon_status]}
      order.save
      changes = order.previous_changes
      if changes.present?
        tracking = TrackingHistory.find_or_initialize_by(date_tracking: Date.current, user_id: current_user.id)
        changes.each do |key, value|
          next if ['updated_at', 'created_at'].include?(key)

          content = "#{Settings.attribute_change.send(key)} updated #{value[0]} => #{value[1]}"
          tracking.tracking_history_details.build(action_submit: "Update Order #{params[:ticket_number]}", content: content)
        end
        tracking.save
      end
      osi_cas = OsiCa.all.pluck(:code, :limit_value).to_h
      order_infomations = OrderInfomation.total_osi_ca_by_issue_date
      order_infomations.each do |osi|
        osi_ca = osi_cas[osi.osi_ca]
        next if osi_ca.blank?

        if osi_ca.to_i < osi.total_value.to_i
          raise StandardError, "OSI #{osi.osi_ca}: #{osi.total_value.to_i} limit value exceeded."
        end
      end
    rescue StandardError => e
      @errors << e.message
      raise ActiveRecord::Rollback
    end
    return if @errors.present?
    # @orders = OrderInfomation.all
    # @text_search = params['q']['ticket_number_or_osi_ca_or_osi_booker_cont'] rescue ''
    # @q = @orders.ransack(params[:q])
    # result = @q.result.page(params[:page])
    # @orders = @current_per_page == Settings.item_paging_all ? result.per(@orders.count) : result.per(@current_per_page)
    # flash[:success] = 'Orders were updated!'
    # @success = ['Order was updated!!!']
  end

  private

  def insert_order_data(orders)
    orders.each_slice(500) do |data|
      OrderInfomation.upsert_all(data)
    end
  end

  def load_params_download
    @month_export = OrderInfomation.get_month.distinct.map { |e| [e.month, e.month] }.sort
    @year_export  = OrderInfomation.get_year.distinct.map { |e| [e.year, e.year] }.sort
    @month_flt    = OrderInfomation.get_month_flt.distinct.map { |e| [e.month, e.month] }.sort
    @year_flt     = OrderInfomation.get_year_flt.distinct.map { |e| [e.year, e.year] }.sort
    @osi_cas = OsiCa.all.map { |osi| [osi.name, osi.id] }
    @osi_bookers = OsiBooker.all.map { |osi| [osi.name, osi.id] }
  end

  def load_orders
    @orders = OrderInfomation.order(:issue_date).order_by_class.accessible_by(current_ability)
  end

  def read_excel_file(file_path)
    data = []
    file_data = Roo::Spreadsheet.open(file_path)
    file_data.last_row.times.each do |index|

app/views/order_infomations/_order.html.erb
<% @orders.each do |osi| %>
  <tr data-controller="update-orders" >
    <%= form_with url: update_order_order_infomations_path, html: { id: "myForm_#{osi.id}" } do %>
      <%= hidden_field_tag :osi_id, osi.id %>
      <td>
        <div class="text-center">
          <label class="input-checkbox">
            <input data-index="0" name="btSelectItem" type="checkbox" osi-id="<%= osi.id %>">
            <span class="checkmark"></span>
          </label>
        </div>
      </td>
      <td><%= osi.issue_date&.strftime('%d/%m/%Y') %></td>
      <td><%= text_field_tag :flt_date, osi.flt_date&.strftime('%d/%m/%Y'), { class: 'form-control width-fit-content', data: { action: 'change->update-orders#change' }} %></td>
      <td>
        <%= osi.ticket_number %>
        <%= hidden_field_tag :ticket_number, osi.ticket_number %>
      </td>
      <td><%= osi.pax_name %></td>
      <td><%= osi.route %></td>
      <td>
        <%= osi.type_ticket %>
        <%= hidden_field_tag :type_ticket, osi.type_ticket %>
      </td>
      <td><%= osi.pnr %></td>
      <td>
        <%= text_field_tag :coupon_status, osi.coupon_status, { class: 'form-control width-fit-content', data: { action: 'change->update-orders#change' }} %>
      </td>
      <td><%= osi.class_ticket %></td>
      <td>
        <%= text_field_tag :ag, osi.ag, { class: 'form-control width-fit-content', data: { action: 'change->update-orders#change' }} %>
      </td>
      <td>
        <%= text_field_tag :osi_ca, osi.osi_ca, { class: 'form-control width-fit-content', data: { action: 'change->update-orders#change' }} %>
      </td>
      <td>
        <%= text_field_tag :osi_booker, osi.osi_booker, { class: 'form-control width-fit-content', data: { action: 'change->update-orders#change' }} %>
      </td>
      <td><%= osi.fare %></td>
      <td><%= osi.charge %></td>
      <td><%= osi.total_full %></td>
      <td><%= osi.saler %></td>
    <% end %>
  </tr>
<% end %>

app/views/order_infomations/import.turbo_stream.erb
<% if @errors.present? %>
  <%= turbo_stream.update 'errorsMessage' do %>
    <%= render 'layouts/errors_messages', errors: @errors %>
  <% end %>
<% else %>
  <div data-controller="redirect" data-redirect-url-value="<%= order_infomations_path %>">
  </div>
<% end %>

app/views/order_infomations/index.html.erb
<%= render partial: 'layouts/sidebar'%>
<div id="content-wrapper" class="d-flex flex-column">
  <div id="content">
    <%= render partial: 'layouts/nav'%>
    <div class="container-fluid">
      <div class='d-flex justify-content-between'>
        <h1 class="h3 mb-2 text-gray-800">Osi CA</h1>
        <div class='bg-white d-flex'>
          <div class='mr-2'>
            <%= form_with url: import_order_infomations_path, multipart: true, id: 'importCSVForm', class: 'import-store-form' do %>
              <label for="upload-file" class='btn btn-success pointer-events'>Import Excel</label>
              <%= file_field_tag :file, id: 'upload-file' %>
              <%= submit_tag 'submit', class: 'd-none', id: 'import-file' %>
            <% end %>
          </div>
          <div>
            <%= link_to "Export Excel", export_order_infomations_path(format: "xlsx"), class: 'btn btn-success pointer-events' %>
          </div>

        </div>
      </div>
      <div class="card shadow mb-4 js-table-checkbox-delete">
        <div id='flashMessage'>
          <%= render 'layouts/flash_message', flash: flash %>
        </div>
        <div id='errorsMessage'>
        </div>
        <div class="card-body">
          <div class='row'>
            <div class='col-md-2 d-flex'>
              <div class="btn-delete-box mr-2">
                <button type="button" class="btn btn-danger btn-del-min-v1 delete-box" disabled>Delete</button>
              </div>
              <div>
                <%= select_tag(:paging, options_for_select(Settings.item_paging, @current_per_page),
                  class: 'form-control-paging form-select') %>
              </div>
            </div>
            <div class='col-md-10'>
              <div class='d-flex pb-3 justify-content-end'>
                <div id="branches__paging" class="form-group ml-3 row">
                  <%= search_form_for @q, url: order_infomations_path, class: 'd-flex flex-column' do |f| %>
                    <div class='row'>
                      <div class='col-md-3 pb-3 pl-0'>
                        <%= f.search_field :issue_date_gteq, value: params[:q].try(:[], :issue_date_gteq), class: 'form-control ml-2', placeholder: 'Issue Date' %>
                      </div>
                      <div class='col-md-3 pb-3 pl-0'>
                        <%= f.search_field :issue_date_lteq, value: params[:q].try(:[], :issue_date_lteq), class: 'form-control ml-2', placeholder: 'Issue Date' %>
                      </div>
                      <div class='col-md-3 pb-3 pl-0'>
                        <%= f.search_field :flt_date_gteq, value: params[:q].try(:[], :flt_date_gteq), class: 'form-control ml-2', placeholder: 'FLT Date' %>
                      </div>
                      <div class='col-md-3 pb-3 pl-0'>
                        <%= f.search_field :flt_date_lteq, value: params[:q].try(:[], :flt_date_lteq), class: 'form-control ml-2', placeholder: 'FLT Date' %>
                      </div>
                    </div>
                    <div class='row'>
                      <div class='col-md-3 pb-3 pl-0'>
                        <%= f.search_field :type_ticket_cont, value: params[:q].try(:[], :type_ticket_cont), class: 'form-control ml-2', placeholder: 'T' %>
                      </div>
                      <div class='col-md-3 pb-3 pl-0'>
                        <%= f.search_field :class_ticket_cont, value: params[:q].try(:[], :class_ticket_cont), class: 'form-control ml-2', placeholder: 'Class' %>
                      </div>
                      <div class='col-md-3 pb-3 pl-0'>
                        <%= f.search_field :osi_ca_cont, value: params[:q].try(:[], :osi_ca_cont), class: 'form-control ml-2', placeholder: 'Osi Ca' %>
                      </div>
                      <div class='col-md-3 pb-3 pl-0'>
                        <%= f.search_field :osi_booker_cont, value: params[:q].try(:[], :osi_booker_cont), class: 'form-control ml-2', placeholder: 'Osi Booker' %>
                      </div>
                    </div>
                    <div class='row'>
                      <div class='col-md-3 pb-3 pl-0'>
                        <%= f.search_field :saler_cont, value: params[:q].try(:[], :saler_cont), class: 'form-control ml-2', placeholder: 'Saler' %>
                      </div>
                      <div class='col-md-3 pl-0'>
                        <%= f.submit 'Search', class: 'btn btn-secondary btn-outline ml-2' %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th class='text-center'>
                    <label class="input-checkbox checkbox-all m-0 pt-1">
                      <input name="btSelectAll" type="checkbox">
                      <span class="checkmark"></span>
                    </label>
                  </th>
                  <th><%= sort_link(@q, :issue_date, 'Issue Date', default_order: :desc) %></th>
                  <th><%= sort_link(@q, :flt_date, 'FLT Date') %></th>
                  <th><%= sort_link(@q, :ticket_number, 'Ticket Nbr') %></th>
                  <th><%= sort_link(@q, :pax_name, 'Pax Name') %></th>
                  <th><%= sort_link(@q, :route, 'Route') %></th>
                  <th><%= sort_link(@q, :type_ticket, 'T') %></th>
                  <th><%= sort_link(@q, :pnr, 'PNR') %></th>
                  <th><%= sort_link(@q, :coupon_status, 'Coupon Status') %></th>
                  <th><%= sort_link(@q, :class_ticket, 'Class') %></th>
                  <th><%= sort_link(@q, :ag, 'AG') %></th>
                  <th><%= sort_link(@q, :osi_ca, 'OSI CA') %></th>
                  <th><%= sort_link(@q, :osi_booker, 'OSI BOOKER') %></th>
                  <th><%= sort_link(@q, :fare, 'Fare') %></th>
                  <th><%= sort_link(@q, :charge, 'Charge') %></th>
                  <th><%= sort_link(@q, :total_full, 'Total Full') %></th>
                  <th><%= sort_link(@q, :saler, 'Saler') %> </th>
                </tr>
              </thead>
              <tbody id='renderOrder'>
                <%= render 'order', orders: @orders %>
              </tbody>
            </table>
          </div>
          <% if @orders.present? %>
            <div class="pagination-flex-end">
              <%= paginate @orders %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="modalDelete" class="modal fade in" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Confirmation</h5>
        <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">Are you sure you want to delete this record?</div>
      <div class="modal-footer justify-content-center"><button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Close</button><button class="btn btn-danger" id="submitDelete" type="button">Delete</button></div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    // $('#dataTable').DataTable();
    $('#upload-file').change(function(e){
      $('#import-file').click();
    });
    $(".checkbox-all").on("click", function() {
      var checked = $(this).find('input')[0].checked;
      $(this)
      .closest("table")
      .find("tbody :checkbox")
      .prop("checked", checked)
    });
    $("tbody :checkbox").on("click", function() {
      $(this).closest("table")
      .find(".checkbox-all input")
      .prop("checked",
        $(this)
        .closest("table")
        .find("tbody :checkbox:checked").length ==
        $(this)
        .closest("table")
        .find("tbody :checkbox").length
        );
    });
    $(document).on('change', '.input-checkbox input[type="checkbox"]', function() {
      let $tableSelect = $(this).closest('.js-table-checkbox-delete');
      let $selectall = $tableSelect.find('.input-checkbox input[name="btSelectAll"]');
      let itemCheckbox = $tableSelect.find('tbody .input-checkbox input[type="checkbox"]').length;
      let itemCheckboxChecked = $tableSelect.find('tbody .input-checkbox input[type="checkbox"]:checked').length;

      if ($selectall.is(':checked') == true) {
        $tableSelect.find('.btn-del-min-v1').attr('disabled', false);
      } else {
        $tableSelect.find('.btn-del-min-v1').attr('disabled', true);
      }

      if ($(this).attr('name') == 'btSelectAll') {
        $tableSelect.find('.input-checkbox input[type="checkbox"]').prop('checked', this.checked);
      } else {
        if (itemCheckbox == itemCheckboxChecked) {
          $selectall.prop("checked", true);
        } else {
          $selectall.prop("checked", false);
        }

        if (itemCheckboxChecked >=1 ) {
          $tableSelect.find('.btn-del-min-v1').attr('disabled', false);
        } else {
          $tableSelect.find('.btn-del-min-v1').attr('disabled', true);
        }
      }
    });
    $(document).on('click', '.delete-box', function() {
      let osiId = [];
      $(':checkbox:checked').each(function(i) {
        osiId[i] = $(this).attr('osi-id');
      });
      osiId = osiId.filter(x => x !== undefined);
      if(osiId.length > 0){
        $('#modalDelete').modal('show');
      } else {
        $('#notificationModal').modal('show');
      }
    });

    $(document).on('click', '#submitDelete', function() {
      $("#loader").addClass('loader-circle');
      $('#modalDelete').modal('hide');
      let osiId = [];
      $(':checkbox:checked').each(function(i) {
        osiId[i] = $(this).attr('osi-id');
      });
      osiId = osiId.filter(x => x !== undefined);
      $.ajax({
        url: '/order_infomations/delete_order',
        type:'DELETE',
        dataType:'script',
        data: {
          ids: JSON.stringify(osiId),
        },
        success: function(){
          return true;
        }
      });
    });

    $(document).on('click', '.save-order', function() {
      $('#update_order').submit();
    });
  });

</script>

app/views/order_infomations/update_order.turbo_stream.erb
<%= turbo_stream.update 'errorsMessage' do %>
  <%= render 'layouts/errors_messages', errors: @errors %>
<% end %>