config/routes.rb
Rails.application.routes.draw do
  get 'healthcheck', to: proc { [200, {}, ['']] }

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
  }
  devise_scope :user do
    post 'users/sign_up', to: 'devise/registrations#create'
    get 'users/:id/edit', to: 'users/registrations#edit', as: :edit_other_user_registration
    match 'users/:id', to: 'users/registrations#update', via: [:patch, :put], as: :other_user_registration
    delete 'users/:id', to: 'users/registrations#destroy', as: :destroy_other_user_registration
  end

  # Defines the root path route ("/")
  root "homes#dashboard"
  resources :users, only: [:index]
  resources :osi_cas do
    collection do
      delete :delete_osis
    end
  end
  resources :osi_bookers do
    collection do
      delete :delete_osis
    end
  end
  resources :order_infomations do
    collection do
      post   :import
      get    :export
      delete :delete_order
      get    :download
      post   :download_data
      post   :update_order
      get    :ajax_download_data
    end
  end
  delete '/delete_users', to: 'users#delete_users'
  resources :tracking_histories, only: [:index, :show]
  get 'export_osi_ca', to: 'homes#download_osi', as: :export_osi_ca
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger show-error">
    <ul class='mb-0'>
      <% model.errors.messages.each do |attr, msg| %>
        <% next if msg.blank? %>
        <li class="error_notice list-unstyled"><%= model.errors.full_messages_for(attr).first.html_safe %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_errors_messages.html.erb
<% if @errors.present? %>
  <div class="alert alert-danger show-error">
    <ul class='mb-0'>
      <% @errors.each do |msg| %>
        <% next if msg.blank? %>
        <li class="error_notice list-unstyled"><%= msg.html_safe %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @success.present? %>
  <div class="alert alert-success">
    <ul class='mb-0'>
      <% @success.each do |msg| %>
        <% next if msg.blank? %>
        <li class="error_notice list-unstyled"><%= msg.html_safe %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Skypro 2023</span>
    </div>
  </div>
</footer>
<!-- Bootstrap core JavaScript-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.3/js/dataTables.bootstrap5.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-notify/0.2.0/js/bootstrap-notify.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.43/moment-timezone-with-data.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/3.0.5/daterangepicker.min.js"></script>
<!-- <script type="text/javascript">
  $(function () {
    $('[data-toggle="tooltip"]').tooltip();
  })

  $(document).ready(function() {
    $('[rel="tooltip"]').tooltip();
  })
</script> -->
<script type="text/javascript">
  setTimeout(function() {
    $('#flashMessage').fadeOut('fast');
  }, 5000);

  // setTimeout(function() {
  //   $('#errorsMessage').fadeOut('fast');
  // }, 15000);
  $(document).on('change', '#paging', function() {
    let searchUrl = window.location.search;
    searchUrl = searchUrl.substr(1);
    searchUrl = searchUrl.replace(/page=\d*\&?/g, '');
    const paging = 'paging='+ $(this).val();
    if (searchUrl.includes('paging=')) {
      searchUrl = searchUrl.replace(/paging=\w*/g, paging);
    } else if (searchUrl.length === 0) {
      searchUrl = paging;
    } else {
      searchUrl += `&${paging}`;
    }
    const href = window.location.origin + window.location.pathname + `?${searchUrl}`;
    window.location.href = href;
  });
</script>

app/views/layouts/_header.html.erb
<link rel="icon" type="image/png" href="/static/imgs/favi-icon.png">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<link href='https://cdn.datatables.net/1.13.3/css/dataTables.bootstrap5.min.css' rel='stylesheet' >
<script
  src="https://code.jquery.com/jquery-3.6.3.min.js"
  integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js" type="text/javascript"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" rel="stylesheet" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-datalabels/1.0.0/chartjs-plugin-datalabels.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/3.0.5/daterangepicker.min.css" rel="stylesheet" />

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <!-- Sidebar Toggle (Topbar) -->
  <form class="form-inline">
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
    </button>
  </form>
  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">
    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name %></span>
      <%= image_tag("undraw_profile.svg", { class: 'img-profile rounded-circle' }) %>
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
        aria-labelledby="userDropdown">
        <%= link_to 'Logout',destroy_user_session_path, method: 'delete', class: "d-link dropdown-item"%>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center logo-header" href="/">
    <img src="/static/imgs/logo.jpg" class='wh-100' alt="">
  </a>
  <!-- Divider -->
  <hr class="sidebar-divider my-0">
  <!-- Nav Item - Dashboard -->
  <li class="nav-item">
    <%= link_to root_path, class: 'nav-link' do %>
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span>
    <% end %>
  </li>
  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Heading -->
  <% if can? :read, User %>
    <div class="sidebar-heading">
      Accounts
    </div>
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
        aria-expanded="true" aria-controls="collapseTwo">
        <i class="fas fa-users"></i>
      <span>Account Managements</span>
      </a>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <%= link_to 'List Users', users_path, class: 'collapse-item' %>
          <% if (can? :create, User) %>
            <%= link_to 'Create User', new_user_registration_path, class: 'collapse-item' %>
          <% end %>
        </div>
      </div>
    </li>
    <hr class="sidebar-divider">
  <% end %>
  <div class="sidebar-heading">
    OSI CA
  </div>
  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
      aria-expanded="true" aria-controls="collapsePages">
    <i class="fas fa-fw fa-folder"></i>
    <span>OSI CAS</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <%= link_to 'List Osi CA', osi_cas_path,class: 'collapse-item' %>
        <% if (can? :create, OsiCa) %>
          <%= link_to 'Create Osi CA', new_osi_ca_path,class: 'collapse-item' %>
        <% end %>
      </div>
    </div>
  </li>
  <hr class="sidebar-divider">
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBooker"
      aria-expanded="true" aria-controls="collapseBooker">
    <i class="fas fa-window-restore"></i>
    <span>OSI Bookers</span>
    </a>
    <div id="collapseBooker" class="collapse" aria-labelledby="headingBooker" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <%= link_to 'List Osi Bookers', osi_bookers_path, class: 'collapse-item' %>
        <% if (can? :create, OsiCa) %>
          <%= link_to 'Create Osi Booker', new_osi_booker_path, class: 'collapse-item' %>
        <% end %>
      </div>
    </div>
  </li>

  <hr class="sidebar-divider">
  <!-- Nav Item - Charts -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseOrder"
      aria-expanded="true" aria-controls="collapseOrder">
    <i class="fas fa-plane-departure"></i>
    <span>Orders</span>
    </a>
    <div id="collapseOrder" class="collapse" aria-labelledby="headingOrder" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <%= link_to 'Orders', order_infomations_path, class: 'collapse-item' %>
        <%= link_to 'Download Orders', download_order_infomations_path, class: 'collapse-item' %>
      </div>
    </div>
  </li>
  <% if (can? :manage, TrackingHistory) %>
    <hr class="sidebar-divider">
    <!-- Nav Item - Charts -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseHistories"
        aria-expanded="true" aria-controls="collapseHistories">
      <i class="fas fa-history"></i>
      <span>Histories</span>
      </a>
      <div id="collapseHistories" class="collapse" aria-labelledby="headingOrder" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <%= link_to 'List Histories', tracking_histories_path, class: 'collapse-item' %>
        </div>
      </div>
    </li>
  <% end %>
  <!-- Nav Item - Tables -->
  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>
<!-- End of Sidebar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkyOsi</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <meta name="turbo-visit-control" content="reload">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
    <%= render 'layouts/header' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id="page-top">
    <div id="wrapper">
      <%= yield %>
    </div>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="login.html">Logout</a>
          </div>
        </div>
      </div>
    </div>
  </body>
  <%= render 'layouts/footer' %>

</html>